### ISSUE TITLE
[Tracking] Updates to template

### ISSUE THREAD

**Issue by Rumyra** [mdn/project-template#6]
- [x] Code of conduct
- [x] Contribution guide
  - [x] Move pull request paragraph to the pr guidelines work https://github.com/mdn/project-template/issues/7
- [x] Community participation roles - move to MDN https://github.com/mdn/project-template/issues/8
  - [x] 'Roles' & 'stepping down' should be same level
  - [x] Community participant and contributor squash into one
  - [x] Roles -> Levels at top community member/contributor, spotlight contributor, maintainer, owner
  - [x] Specialised roles -> Community manager (make more generic), Invited Experts,
- [x] License - if in doubt attribute (also MDN page) https://github.com/mdn/project-template/issues/9
- [x] Reviewing - move the majority to PR guidelines docs https://github.com/mdn/project-template/issues/10
  - [x] Keep the markdown file and link to pr guidelines, add any specifics per repo

**Comment by bsmth** [comment]
I think all of these are done now. We should check the contributor roles doc, whether we want this in all repos or on one page on MDN, particularly the processes; if this is something we update (how to nominate, links to issue templates etc.) we'll have to update everywhere. The content is good, but maybe we can add to [community](https://developer.mozilla.org/en-US/docs/MDN/Community) and link to it.

**Comment by schalkneethling** [comment]
> I think all of these are done now. We should check the contributor roles doc, whether we want this in all repos or on one page on MDN, particularly the processes; if this is something we update (how to nominate, links to issue templates etc.) we'll have to update everywhere. The content is good, but maybe we can add to [community](https://developer.mozilla.org/en-US/docs/MDN/Community) and link to it.

I %100 agree
